version: 0.2

env:
  shell: bash
  
phases:
  build:
    on-failure: ABORT
    commands:
             - apt update -yq
             - apt install -yq uuid
             - apt install -yq libguestfs-tools squashfs-tools curl mkisofs cdrecord util-linux xorriso xz-utils
             - apt install -yq virtualbox virtualbox-guest-additions-iso   
             - ./mkg compact minimal minimal_size gentoo.iso gui=false cleanup remove_dvi

artifacts:
  files: 
  - gentoo.iso
  name: gentoo_gnome_$(date +%Y-%m-%d)_x86_64.iso
